name: first-workflow
on: workflow_dispatch
jobs:
  firstjob: 
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello world"
      - name: Print done
        run: echo "Goodbye"
